language: node_js
node_js:
- '8'
cache: yarn
addons:
  apt:
    packages:
    - g++-4.8
    sources:
    - ubuntu-toolchain-r-test
env:
  secure: YlGEpaf6elXlx/SA1AF6StYbcxw8LP+35RgNGkUDOvlahelSLOyA3AWD4ZvwW8vEeASarGE9oNxzgb45RCSqfCF+zvUhrLsWraWNvmthA/SkP464Y5eriNdLssdd9oovvBxA6JlOtxowRqNoCXfLk88xNqnqkSU9ldR4bMP6u1CbXqCp13CXEKLeqkxo1aAgkt+9DJ4XduOV4k5/aG8zHTg5aQiWv1qExJNipTqhdg5pqVZO/Lvt6shqqrV1JQ0IqlGIkh6DfVZXYLVZnvjHhapjl+R+dJ3+5wuxWB6VtHO2wqKPOU6Q1I922ab6QKt45252oQQ1+X9qj1beYLldXbL3qMZJi9FOK5/dxHGddSUtXomoAq4qFKjusMWrj2ncUT1mK43+fwCYIcfljyfvtqfqGLWOCJSrCWOc0xl4QdDRAsBabhinwn2SuktyPoVQHWFSU9IlOJukNsoNr/10xamJRr+IfBe+UflGXNKOPBDar2+y3Vo3aVjqfdzhIqlSoXA+JUst1xc27k3BlGwM+cxbIWfNRGD6gT3iA3vMlXm2rax+MJBe7TN9Py9fNO5cBPukywLY5L9hM9HKZbPSbpc5KGKObmvtxoJXXySfBRD4vec5hBFpkNGEikn/jxrimacAAgK9KR5vvEeTN4r1HgE07lKujMReWiSzaF7dm1Y=
git:
  depth: false
  submodules: false
branches:
  only:
  - develop
before_install:
- sed -i 's/git@github.com:/https:\/\/${GITHUB_USERNAME}:${GIT_TOKEN}@github.com\//'
  .gitmodules
- git submodule update --init --recursive
before_script:
- yarn global add firebase-tools
- yarn global add gatsby
script:
- yarn build-staging
after_success:
- firebase deploy -P staging --token=${FIREBASE_API_TOKEN}
