version: 2
jobs:
  build-staging:
    docker:
      - image: circleci/node:latest
    filters:
      branches:
        only: develop
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-
          # fallback to using the latest cache if no exact match is found
          - dependencies-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-
      - run:
          name: Gatsby build site
          command: yarn build-staging
      - run:
          name: Deploy to Firebase
          command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive -P staging
  build-production:
    docker:
      - image: circleci/node:latest
    filters:
      branches:
        only: master
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-
          # fallback to using the latest cache if no exact match is found
          - dependencies-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-
      - run:
          name: Gatsby build site
          command: yarn build
      - run:
          name: Deploy to Firebase
          command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive -P default
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-staging:
          filters:
            branches:
              only: develop
      - build-production:
          requires:
            - build-staging
          filters:
            branches:
              only: master
