workflows:
  version: 2
  dev_stage_pre-prod:
    jobs:
      - staging_site:
          docker:
            - image: circleci/node:latest
          steps:
            - checkout
            - restore_cache:
                keys:
                  - dependencies-
                    - dependencies-
            - run:
                name: Install Dependencies
                command: yarn install
            - save_cache:
                paths:
                  - node_modules
                key: dependencies-
            - run:
                name: Gatsby build site
                command: yarn build-staging
            - run:
                name: Deploy to Firebase
                command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive -P staging
          filters:
            branches:
              only:
                - develop
      - production_site:
          docker:
            - image: circleci/node:latest
          steps:
            - checkout
            - restore_cache:
                keys:
                  - dependencies-
                    - dependencies-
            - run:
                name: Install Dependencies
                command: yarn install
            - save_cache:
                paths:
                  - node_modules
                key: dependencies-
            - run:
                name: Gatsby build site
                command: yarn build-staging
            - run:
                name: Deploy to Firebase
                command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive -P staging
          filters:
            branches:
              only: master
